summary: Update the gce test bucket

systems: [ubuntu-20.04-64]

restore: |
    rm -rf snapd spread-amd64.tar.gz spread
   
execute: |
    apt install -y xdelta3
    wget https://storage.googleapis.com/snapd-spread-tests/spread/spread-amd64.tar.gz
    tar -xvzf spread-amd64.tar.gz

    mkdir -p ~/.config/gcloud
    cp sa.json ~/.config/gcloud/application_default_credentials.json

    git clone https://github.com/snapcore/snapd.git
    mv sa.json snapd

    ( cd snapd && ../spread google:tests/nightly/upload-snapd-to-gce )
