name: Jobs
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run test
      run: |
          BRANCH="${GITHUB_REF##*/}"
          export PROJECT_PATH="$(pwd)"
          ./branches/"$BRANCH"/run-checks