name: Jobs
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run test
      env:
          IMAGE_BAKER_SA: ${{ secrets.IMAGE_BAKER_SA }}
      run: |
          BRANCH="${GITHUB_REF##*/}"
          export PROJECT_PATH="$(pwd)"
          if [[ "$BRANCH" == gce-* ]]; then
              echo "$IMAGE_BAKER_SA" > ./branches/"$BRANCH"/sa.json
          fi
          ./branches/"$BRANCH"/run-checks
