name: Jobs
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Cleanup job workspace
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: master

    - name: Run test
      env:
          IMAGE_BAKER_SA: ${{ secrets.IMAGE_BAKER_SA }}
          LAUNCHPAD_ID_RSA: ${{ secrets.LAUNCHPAD_ID_RSA }}
          LAUNCHPAD_COOKIES: ${{ secrets.LAUNCHPAD_COOKIES }}
          S390X_ENDPOINT: ${{ secrets.S390X_ENDPOINT }}
          S390X_PASSWORD: ${{ secrets.S390X_PASSWORD }}
      run: |
          BRANCH="${GITHUB_REF##*/}"
          export PROJECT_PATH="$(pwd)"
          export BRANCH_PATH="$PROJECT_PATH"/branches/"$BRANCH"

          cd "$BRANCH_PATH"
          if [[ "$BRANCH" == gce-update-* ]] || [[ "$BRANCH" == update-gce-* ]] || [[ "$BRANCH" == build-spread* ]]; then
              echo "$IMAGE_BAKER_SA" > sa.json
          fi
          if [ "$BRANCH" = "snapd-vendor-sync" ]; then
              echo "$LAUNCHPAD_ID_RSA" > target/tasks/snapd-vendor-sync/id_rsa
              echo "$LAUNCHPAD_COOKIES" > target/tasks/snapd-vendor-sync/cookies.txt
          fi

          ./run-checks
